commerce_user:
    resource: "@CommerceUserBundle/Resources/config/routing.yml"
    prefix:   /

commerce_admin:
    resource: "@CommerceAdminBundle/Controller/"
    type:     annotation
    prefix:   /

